language: python
python:
  - "3.6"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: nosetests --cover-branches --with-coverage --cover-erase --cover-package proj_1 --coverage proj_2
after_success:
  coveralls
